# Definitions

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from qutip import *
qutip.settings.has_mkl = False

## Qubits

### Pauli Matricies

$\hat\sigma_x$

In [2]:
sigmax()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

$\hat\sigma_y$

In [3]:
sigmay()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

$\hat\sigma_z$

In [4]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

### States

In [5]:
up = basis(2, 0)
down = basis(2, 1)

$|\uparrow\rangle$

In [6]:
up

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

$|\downarrow\rangle$

In [7]:
down

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

$\hat \sigma_z|\uparrow\rangle = +1|\uparrow\rangle$

In [8]:
sigmaz() * up

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

$\hat \sigma_z|\downarrow\rangle = -1|\downarrow\rangle$

In [9]:
sigmaz() * down

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.]
 [-1.]]

## Spin Matricies
$\hat S_i = \frac\hbar 2\hat\sigma_i,\quad\hbar=1$

In [12]:
jmat(.5, 'x')

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.  0.5]
 [0.5 0. ]]

In [13]:
jmat(.5, 'y')

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j  0.-0.5j]
 [0.+0.5j 0.+0.j ]]

In [15]:
jmat(.5, 'z')

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.5  0. ]
 [ 0.  -0.5]]

$\hat S_z|\uparrow\rangle = \frac12|\uparrow\rangle$

In [17]:
jmat(.5, 'z') * up

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.5]
 [0. ]]

$\hat S_z|\downarrow\rangle = -\frac12|\downarrow\rangle$

In [19]:
jmat(.5, 'z') * down

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0. ]
 [-0.5]]